app:
  source: "urn::omiga::bittrex-processor"

exchange:
  id: "bittrex"

pulsar:
  url: "pulsar://localhost:6650"
  subscriptionName: "bittrex-processor"
  producerName: "bittrex-processor"
  operationTimeout: 30s
  connectionTimeout: 30s

postgres:
  connectionString: "postgres://postgres:12345678@localhost/venue"
  maxOpenConns: 5

bittrex:
  apiKey: ""
  secretKey: ""
