// Code generated by ent, DO NOT EDIT.

//go:build tools
// +build tools

// Package internal holds a loadable version of the latest schema.
package internal

const Schema = `{"Schema":"github.com/omiga-group/omiga/src/order/shared/repositories/schema","Package":"github.com/omiga-group/omiga/src/order/shared/repositories","Schemas":[{"name":"Order","config":{"Table":""}}],"Features":["privacy","entql","schema/snapshot","sql/schemaconfig","sql/lock","sql/modifier","sql/execquery","sql/upsert","sql/versioned-migration"]}`
