# syntax = docker/dockerfile:1.4.1
FROM node:18
LABEL maintainer="morteza@omiga.com.au"

RUN apt-get update -y \
  && apt-get upgrade -y \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

RUN npx playwright install-deps
