app:
  source: "urn::omiga::kucoin-processor"

exchange:
  id: "kucoin"

pulsar:
  url: "pulsar://localhost:6650"
  subscriptionName: "kucoin-processor"
  producerName: "kucoin-processor"
  operationTimeout: 30s
  connectionTimeout: 30s

postgres:
  connectionString: "postgres://postgres:12345678@localhost/venue"
  maxOpenConns: 5

kucoin:
  apiKey: ""
  passphrase: ""
  secretKey: ""
