app:
  source: "urn::omiga::gemini-processor"

pulsar:
  url: "pulsar://localhost:6650"
  subscriptionName: "gemini-processor"
  producerName: "gemini-processor"
  operationTimeout: 30s
  connectionTimeout: 30s

gemini:
  apiUrl: https://api.sandbox.gemini.com/v1
  websocketUrl: wss://api.sandbox.gemini.com
  timeout: 10
  orderBook:
    markets:
      - market: ETH-PERP
