# syntax = docker/dockerfile:1.4.1
FROM golang:1.19
LABEL maintainer="yadollah.alizadeh.dahanesari@omiga.com.au"

RUN --mount=type=cache,target=/go go install github.com/google/wire/cmd/wire@latest
RUN --mount=type=cache,target=/go go install entgo.io/ent/cmd/ent@latest
RUN --mount=type=cache,target=/go go install github.com/deepmap/oapi-codegen/cmd/oapi-codegen@latest
RUN --mount=type=cache,target=/go go install github.com/golang/mock/mockgen@latest

RUN mkdir -p /src/shared/enterprise \
    mkdir -p /src/shared/clients \
    mkdir -p /src/exchange/shared \
    mkdir -p /src/exchange/gemini-processor

COPY go.mod /src/
COPY go.sum /src/
COPY shared/enterprise /src/shared/enterprise
COPY shared/clients /src/shared/clients
COPY exchange/shared /src/exchange/shared
COPY exchange/gemini-processor /src/exchange/gemini-processor

WORKDIR /src/exchange/gemini-processor

ENV GOFLAGS -mod=mod
RUN --mount=type=cache,target=/go go generate ./...
