// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/omiga-group/omiga/src/order/shared/repositories/runtime.go

const (
	Version = "v0.11.2-0.20220724154107-b60e0f9eac27"           // Version of ent codegen.
	Sum     = "h1:cN+6ASqjhlcEToswhP9onQJLhK1auXJNPuKrDKGRDFE=" // Sum of ent codegen.
)
