version: "3.9"

services:
  order-database-migration:
    image: ${DOCKER_REGISTRY-}orderdatabasemigration
    build:
      context: .
      dockerfile: order/shared/cli/Dockerfile
      target: final
    restart: on-failure
    environment:
      OMIGA_POSTGRES_CONNECTIONSTRING: "postgres://postgres:12345678@postgres/order"
    depends_on:
      - postgres
    profiles:
      - core
      - order
      - all
    networks:
      - omiga_network

  order-api:
    image: ${DOCKER_REGISTRY-}orderapi
    build:
      context: .
      dockerfile: order/order-api/Dockerfile
      target: final
    restart: unless-stopped
    environment:
      OMIGA_APP_LISTENINGINTERFACE: ":80"
      OMIGA_POSTGRES_CONNECTIONSTRING: "postgres://postgres:12345678@postgres/order"
      OMIGA_PULSAR_URL: ${OMIGA_PULSAR_URL:-pulsar://pulsar:6650}
      OMIGA_PULSAR_ENABLEAUTHENTICATIONOAUTH2: ${OMIGA_PULSAR_ENABLEAUTHENTICATIONOAUTH2}
      OMIGA_PULSAR_AUTHENTICATION_TYPE: ${OMIGA_PULSAR_AUTHENTICATION_TYPE}
      OMIGA_PULSAR_AUTHENTICATION_ISSUERURL: ${OMIGA_PULSAR_AUTHENTICATION_ISSUERURL}
      OMIGA_PULSAR_AUTHENTICATION_AUDIENCE: ${OMIGA_PULSAR_AUTHENTICATION_AUDIENCE}
      OMIGA_PULSAR_AUTHENTICATION_PRIVATEKEY: ${OMIGA_PULSAR_AUTHENTICATION_PRIVATEKEY}
      OMIGA_PULSAR_AUTHENTICATION_CLIENTID: ${OMIGA_PULSAR_AUTHENTICATION_CLIENTID}
    ports:
      - "10000:80"
    depends_on:
      - postgres
      - order-database-migration
      - pulsar
    profiles:
      - order
      - all
    networks:
      - omiga_network

  order-processor:
    image: ${DOCKER_REGISTRY-}orderprocessor
    build:
      context: .
      dockerfile: order/order-processor/Dockerfile
      target: final
    restart: unless-stopped
    environment:
      OMIGA_POSTGRES_CONNECTIONSTRING: "postgres://postgres:12345678@postgres/order"
      OMIGA_PULSAR_URL: ${OMIGA_PULSAR_URL:-pulsar://pulsar:6650}
      OMIGA_PULSAR_ENABLEAUTHENTICATIONOAUTH2: ${OMIGA_PULSAR_ENABLEAUTHENTICATIONOAUTH2}
      OMIGA_PULSAR_AUTHENTICATION_TYPE: ${OMIGA_PULSAR_AUTHENTICATION_TYPE}
      OMIGA_PULSAR_AUTHENTICATION_ISSUERURL: ${OMIGA_PULSAR_AUTHENTICATION_ISSUERURL}
      OMIGA_PULSAR_AUTHENTICATION_AUDIENCE: ${OMIGA_PULSAR_AUTHENTICATION_AUDIENCE}
      OMIGA_PULSAR_AUTHENTICATION_PRIVATEKEY: ${OMIGA_PULSAR_AUTHENTICATION_PRIVATEKEY}
      OMIGA_PULSAR_AUTHENTICATION_CLIENTID: ${OMIGA_PULSAR_AUTHENTICATION_CLIENTID}
    depends_on:
      - postgres
      - order-database-migration
      - pulsar
    profiles:
      - order
      - all
    networks:
      - omiga_network
