version: "3.8"

services:
  order-database-migration:
    image: ${DOCKER_REGISTRY-}orderdatabasemigration
    build:
      context: .
      dockerfile: order/shared/repositories/cli/Dockerfile
      target: local
    restart: unless-stopped
    depends_on:
      - postgresdb
    networks:
      - omiga_network

  order-api:
    image: ${DOCKER_REGISTRY-}orderapi
    build:
      context: .
      dockerfile: order/order-api/Dockerfile
      target: local
    restart: unless-stopped
    depends_on:
      - postgresdb
      - pulsar
      - order-database-migration
    networks:
      - omiga_network

  order-processor:
    image: ${DOCKER_REGISTRY-}orderprocessor
    build:
      context: .
      dockerfile: order/order-processor/Dockerfile
      target: local
    restart: unless-stopped
    depends_on:
      - postgresdb
      - pulsar
      - order-database-migration
    networks:
      - omiga_network
