version: "3.8"

services:
  postgresdb-order-database-initializer:
    image: postgres:14.4-alpine
    hostname: postgresdb
    restart: on-failure
    command: psql -h postgres.localhost -U postgres -c "CREATE DATABASE \"order\";"
    environment:
      PGPASSWORD: 12345678
    depends_on:
      - postgresdb
    networks:
      - omiga_network

  order-database-migration:
    image: ${DOCKER_REGISTRY-}orderdatabasemigration
    build:
      context: .
      dockerfile: order/shared/repositories/cli/Dockerfile
      target: local
    restart: on-failure
    depends_on:
      - postgresdb-order-database-initializer
    networks:
      - omiga_network

  order-api:
    image: ${DOCKER_REGISTRY-}orderapi
    build:
      context: .
      dockerfile: order/order-api/Dockerfile
      target: local
    restart: unless-stopped
    depends_on:
      - postgresdb
      - order-database-migration
      - pulsar
    networks:
      - omiga_network

  order-processor:
    image: ${DOCKER_REGISTRY-}orderprocessor
    build:
      context: .
      dockerfile: order/order-processor/Dockerfile
      target: local
    restart: unless-stopped
    depends_on:
      - postgresdb
      - order-database-migration
      - pulsar
    networks:
      - omiga_network
