version: "3.8"

services:
  exchange-database-migration:
    image: ${DOCKER_REGISTRY-}exchangedatabasemigration
    build:
      context: .
      dockerfile: exchange/shared/repositories/cli/Dockerfile
      target: local
    restart: on-failure
    environment:
      OMIGA_POSTGRES_CONNECTIONSTRING: "postgres://postgres:12345678@postgres/exchange"
    depends_on:
      - postgres
    networks:
      - omiga_network

  exchange-api:
    image: ${DOCKER_REGISTRY-}exchangeapi
    build:
      context: .
      dockerfile: exchange/exchange-api/Dockerfile
      target: local
    restart: unless-stopped
    environment:
      OMIGA_APP_LISTENINGINTERFACE: ":80"
      OMIGA_POSTGRES_CONNECTIONSTRING: "postgres://postgres:12345678@postgres/exchange"
    ports:
      - "11000:80"
    depends_on:
      - postgres
      - exchange-database-migration
    networks:
      - omiga_network

  omiga-processor1:
    image: ${DOCKER_REGISTRY-}omigaprocessor1
    build:
      context: .
      dockerfile: exchange/omiga-processor/Dockerfile
      target: local
    restart: unless-stopped
    command: /bin/omiga-processor start --name omiga-exchange1
    environment:
      OMIGA_PULSAR_URL: "pulsar://pulsar:6650"
    depends_on:
      - postgres
      - exchange-database-migration
      - pulsar
    networks:
      - omiga_network

  omiga-processor2:
    image: ${DOCKER_REGISTRY-}omigaprocessor2
    build:
      context: .
      dockerfile: exchange/omiga-processor/Dockerfile
      target: local
    restart: unless-stopped
    command: /bin/omiga-processor start --name omiga-exchange2
    environment:
      OMIGA_PULSAR_URL: "pulsar://pulsar:6650"
    depends_on:
      - postgres
      - exchange-database-migration
      - pulsar
    networks:
      - omiga_network

  omiga-processor3:
    image: ${DOCKER_REGISTRY-}omigaprocessor3
    build:
      context: .
      dockerfile: exchange/omiga-processor/Dockerfile
      target: local
    restart: unless-stopped
    command: /bin/omiga-processor start --name omiga-exchange3
    environment:
      OMIGA_PULSAR_URL: "pulsar://pulsar:6650"
    depends_on:
      - postgres
      - exchange-database-migration
      - pulsar
    networks:
      - omiga_network

  binance-processor:
    image: ${DOCKER_REGISTRY-}binanceprocessor
    build:
      context: .
      dockerfile: exchange/binance-processor/Dockerfile
      target: local
    restart: unless-stopped
    environment:
      OMIGA_PULSAR_URL: "pulsar://pulsar:6650"
    depends_on:
      - postgres
      - exchange-database-migration
      - pulsar
    networks:
      - omiga_network

  ftx-processor:
    image: ${DOCKER_REGISTRY-}ftxprocessor
    build:
      context: .
      dockerfile: exchange/ftx-processor/Dockerfile
      target: local
    restart: unless-stopped
    environment:
      OMIGA_PULSAR_URL: "pulsar://pulsar:6650"
    depends_on:
      - postgres
      - exchange-database-migration
      - pulsar
    networks:
      - omiga_network

  coingeko:
    image: ${DOCKER_REGISTRY-}coingeko
    build:
      context: .
      dockerfile: exchange/coingeko/Dockerfile
      target: local
    restart: unless-stopped
    environment:
      OMIGA_POSTGRES_CONNECTIONSTRING: "postgres://postgres:12345678@postgres/exchange"
    depends_on:
      - postgres
      - exchange-database-migration
    networks:
      - omiga_network
