version: "3.8"

services:
  postgres-exchange-database-initializer:
    image: postgres:14.4-alpine
    restart: on-failure
    command: psql -h postgres -U postgres -c "CREATE DATABASE \"exchange\";"
    environment:
      PGPASSWORD: 12345678
    depends_on:
      - postgres
    networks:
      - omiga_network

  exchange-database-migration:
    image: ${DOCKER_REGISTRY-}exchangedatabasemigration
    build:
      context: .
      dockerfile: exchange/shared/repositories/cli/Dockerfile
      target: local
    restart: on-failure
    environment:
      OMIGA_ENVIRONMENT: dockercompose
    depends_on:
      - postgres-exchange-database-initializer
    networks:
      - omiga_network

  omiga1-processor:
    image: ${DOCKER_REGISTRY-}omiga1processor
    build:
      context: .
      dockerfile: exchange/omiga-processor/Dockerfile
      target: local
    restart: unless-stopped
    command: /bin/omiga-processor start --name omiga-exchange1
    environment:
      OMIGA_ENVIRONMENT: dockercompose
    depends_on:
      - postgres
      - exchange-database-migration
      - pulsar
    networks:
      - omiga_network

  binance-processor:
    image: ${DOCKER_REGISTRY-}binanceprocessor
    build:
      context: .
      dockerfile: exchange/binance-processor/Dockerfile
      target: local
    restart: unless-stopped
    environment:
      OMIGA_ENVIRONMENT: dockercompose
    depends_on:
      - postgres
      - exchange-database-migration
      - pulsar
    networks:
      - omiga_network

  ftx-processor:
    image: ${DOCKER_REGISTRY-}ftxprocessor
    build:
      context: .
      dockerfile: exchange/ftx-processor/Dockerfile
      target: local
    restart: unless-stopped
    environment:
      OMIGA_ENVIRONMENT: dockercompose
    depends_on:
      - postgres
      - exchange-database-migration
      - pulsar
    networks:
      - omiga_network
