version: "3.9"

services:
  exchange-database-migration:
    image: ${DOCKER_REGISTRY-}exchangedatabasemigration
    build:
      context: .
      dockerfile: exchange/shared/cli/Dockerfile
      target: local
    restart: on-failure
    environment:
      OMIGA_POSTGRES_CONNECTIONSTRING: "postgres://postgres:12345678@postgres/exchange"
    depends_on:
      - postgres
    profiles:
      - core
      - exchange
      - all
    networks:
      - omiga_network

  exchange-api:
    image: ${DOCKER_REGISTRY-}exchangeapi
    build:
      context: .
      dockerfile: exchange/exchange-api/Dockerfile
      target: local
    restart: unless-stopped
    environment:
      OMIGA_APP_LISTENINGINTERFACE: ":80"
      OMIGA_POSTGRES_CONNECTIONSTRING: "postgres://postgres:12345678@postgres/exchange"
    ports:
      - "11000:80"
    depends_on:
      - postgres
      - exchange-database-migration
    profiles:
      - exchange
      - all
    networks:
      - omiga_network

  coingecko-processor:
    image: ${DOCKER_REGISTRY-}coingeckoprocessor
    build:
      context: .
      dockerfile: exchange/coingecko-processor/Dockerfile
      target: local
    restart: unless-stopped
    environment:
      OMIGA_POSTGRES_CONNECTIONSTRING: "postgres://postgres:12345678@postgres/exchange"
    depends_on:
      - postgres
      - exchange-database-migration
    profiles:
      - exchange
      - all
    networks:
      - omiga_network

  binance-processor:
    image: ${DOCKER_REGISTRY-}binanceprocessor
    build:
      context: .
      dockerfile: exchange/binance-processor/Dockerfile
      target: local
    restart: unless-stopped
    environment:
      OMIGA_PULSAR_URL: ${OMIGA_PULSAR_URL:-pulsar://pulsar:6650}
      OMIGA_PULSAR_ENABLEAUTHENTICATIONOAUTH2: ${OMIGA_PULSAR_ENABLEAUTHENTICATIONOAUTH2}
      OMIGA_PULSAR_AUTHENTICATION_TYPE: ${OMIGA_PULSAR_AUTHENTICATION_TYPE}
      OMIGA_PULSAR_AUTHENTICATION_ISSUERURL: ${OMIGA_PULSAR_AUTHENTICATION_ISSUERURL}
      OMIGA_PULSAR_AUTHENTICATION_AUDIENCE: ${OMIGA_PULSAR_AUTHENTICATION_AUDIENCE}
      OMIGA_PULSAR_AUTHENTICATION_PRIVATEKEY: ${OMIGA_PULSAR_AUTHENTICATION_PRIVATEKEY}
      OMIGA_PULSAR_AUTHENTICATION_CLIENTID: ${OMIGA_PULSAR_AUTHENTICATION_CLIENTID}
      OMIGA_POSTGRES_CONNECTIONSTRING: "postgres://postgres:12345678@postgres/exchange"
    depends_on:
      - postgres
      - exchange-database-migration
      - pulsar
    profiles:
      - exchange
      - all
    networks:
      - omiga_network

  ftx-processor:
    image: ${DOCKER_REGISTRY-}ftxprocessor
    build:
      context: .
      dockerfile: exchange/ftx-processor/Dockerfile
      target: local
    restart: unless-stopped
    environment:
      OMIGA_PULSAR_URL: ${OMIGA_PULSAR_URL:-pulsar://pulsar:6650}
      OMIGA_PULSAR_ENABLEAUTHENTICATIONOAUTH2: ${OMIGA_PULSAR_ENABLEAUTHENTICATIONOAUTH2}
      OMIGA_PULSAR_AUTHENTICATION_TYPE: ${OMIGA_PULSAR_AUTHENTICATION_TYPE}
      OMIGA_PULSAR_AUTHENTICATION_ISSUERURL: ${OMIGA_PULSAR_AUTHENTICATION_ISSUERURL}
      OMIGA_PULSAR_AUTHENTICATION_AUDIENCE: ${OMIGA_PULSAR_AUTHENTICATION_AUDIENCE}
      OMIGA_PULSAR_AUTHENTICATION_PRIVATEKEY: ${OMIGA_PULSAR_AUTHENTICATION_PRIVATEKEY}
      OMIGA_PULSAR_AUTHENTICATION_CLIENTID: ${OMIGA_PULSAR_AUTHENTICATION_CLIENTID}
    depends_on:
      - postgres
      - exchange-database-migration
      - pulsar
    profiles:
      - exchange
      - all
    networks:
      - omiga_network

  gemini-processor:
    image: ${DOCKER_REGISTRY-}geminiprocessor
    build:
      context: .
      dockerfile: exchange/gemini-processor/Dockerfile
      target: local
    restart: unless-stopped
    environment:
      OMIGA_PULSAR_URL: ${OMIGA_PULSAR_URL:-pulsar://pulsar:6650}
      OMIGA_PULSAR_ENABLEAUTHENTICATIONOAUTH2: ${OMIGA_PULSAR_ENABLEAUTHENTICATIONOAUTH2}
      OMIGA_PULSAR_AUTHENTICATION_TYPE: ${OMIGA_PULSAR_AUTHENTICATION_TYPE}
      OMIGA_PULSAR_AUTHENTICATION_ISSUERURL: ${OMIGA_PULSAR_AUTHENTICATION_ISSUERURL}
      OMIGA_PULSAR_AUTHENTICATION_AUDIENCE: ${OMIGA_PULSAR_AUTHENTICATION_AUDIENCE}
      OMIGA_PULSAR_AUTHENTICATION_PRIVATEKEY: ${OMIGA_PULSAR_AUTHENTICATION_PRIVATEKEY}
      OMIGA_PULSAR_AUTHENTICATION_CLIENTID: ${OMIGA_PULSAR_AUTHENTICATION_CLIENTID}
      OMIGA_POSTGRES_CONNECTIONSTRING: "postgres://postgres:12345678@postgres/exchange"
    depends_on:
      - postgres
      - exchange-database-migration
      - pulsar
    profiles:
      - exchange
      - all
    networks:
      - omiga_network

  kraken-processor:
    image: ${DOCKER_REGISTRY-}krakenprocessor
    build:
      context: .
      dockerfile: exchange/kraken-processor/Dockerfile
      target: local
    restart: unless-stopped
    environment:
      OMIGA_PULSAR_URL: ${OMIGA_PULSAR_URL:-pulsar://pulsar:6650}
      OMIGA_PULSAR_ENABLEAUTHENTICATIONOAUTH2: ${OMIGA_PULSAR_ENABLEAUTHENTICATIONOAUTH2}
      OMIGA_PULSAR_AUTHENTICATION_TYPE: ${OMIGA_PULSAR_AUTHENTICATION_TYPE}
      OMIGA_PULSAR_AUTHENTICATION_ISSUERURL: ${OMIGA_PULSAR_AUTHENTICATION_ISSUERURL}
      OMIGA_PULSAR_AUTHENTICATION_AUDIENCE: ${OMIGA_PULSAR_AUTHENTICATION_AUDIENCE}
      OMIGA_PULSAR_AUTHENTICATION_PRIVATEKEY: ${OMIGA_PULSAR_AUTHENTICATION_PRIVATEKEY}
      OMIGA_PULSAR_AUTHENTICATION_CLIENTID: ${OMIGA_PULSAR_AUTHENTICATION_CLIENTID}
      OMIGA_POSTGRES_CONNECTIONSTRING: "postgres://postgres:12345678@postgres/exchange"
    depends_on:
      - postgres
      - exchange-database-migration
      - pulsar
    profiles:
      - exchange
      - all
    networks:
      - omiga_network
