version: "3.8"

services:
  postgresdb-exchange-database-initializer:
    image: postgres:14.4-alpine
    hostname: postgresdb
    restart: on-failure
    command: psql -h postgres.localhost -U postgres -c "CREATE DATABASE \"exchange\";"
    environment:
      PGPASSWORD: 12345678
    depends_on:
      - postgresdb
    networks:
      - omiga_network

  exchange-database-migration:
    image: ${DOCKER_REGISTRY-}exchangedatabasemigration
    build:
      context: .
      dockerfile: exchange/shared/repositories/cli/Dockerfile
      target: local
    restart: on-failure
    depends_on:
      - postgresdb-exchange-database-initializer
    networks:
      - omiga_network

  binance-processor:
    image: ${DOCKER_REGISTRY-}binanceprocessor
    build:
      context: .
      dockerfile: exchange/binance-processor/Dockerfile
      target: local
    restart: unless-stopped
    depends_on:
      - postgresdb
      - exchange-database-migration
      - pulsar
    networks:
      - omiga_network

  ftx-processor:
    image: ${DOCKER_REGISTRY-}ftxprocessor
    build:
      context: .
      dockerfile: exchange/ftx-processor/Dockerfile
      target: local
    restart: unless-stopped
    depends_on:
      - postgresdb
      - exchange-database-migration
      - pulsar
    networks:
      - omiga_network
