// Code generated by ent, DO NOT EDIT.

package entities

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/omiga-group/omiga/src/venue/shared/entities/internal"
	"github.com/omiga-group/omiga/src/venue/shared/entities/predicate"
	"github.com/omiga-group/omiga/src/venue/shared/entities/tradingpair"
)

// TradingPairDelete is the builder for deleting a TradingPair entity.
type TradingPairDelete struct {
	config
	hooks    []Hook
	mutation *TradingPairMutation
}

// Where appends a list predicates to the TradingPairDelete builder.
func (tpd *TradingPairDelete) Where(ps ...predicate.TradingPair) *TradingPairDelete {
	tpd.mutation.Where(ps...)
	return tpd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (tpd *TradingPairDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(tpd.hooks) == 0 {
		affected, err = tpd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TradingPairMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			tpd.mutation = mutation
			affected, err = tpd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(tpd.hooks) - 1; i >= 0; i-- {
			if tpd.hooks[i] == nil {
				return 0, fmt.Errorf("entities: uninitialized hook (forgotten import entities/runtime?)")
			}
			mut = tpd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tpd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (tpd *TradingPairDelete) ExecX(ctx context.Context) int {
	n, err := tpd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (tpd *TradingPairDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: tradingpair.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: tradingpair.FieldID,
			},
		},
	}
	_spec.Node.Schema = tpd.schemaConfig.TradingPair
	ctx = internal.NewSchemaConfigContext(ctx, tpd.schemaConfig)
	if ps := tpd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, tpd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// TradingPairDeleteOne is the builder for deleting a single TradingPair entity.
type TradingPairDeleteOne struct {
	tpd *TradingPairDelete
}

// Exec executes the deletion query.
func (tpdo *TradingPairDeleteOne) Exec(ctx context.Context) error {
	n, err := tpdo.tpd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{tradingpair.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tpdo *TradingPairDeleteOne) ExecX(ctx context.Context) {
	tpdo.tpd.ExecX(ctx)
}
