app:
  source: "urn::omiga::ftx-processor"

pulsar:
  url: "pulsar://localhost:6650"
  subscriptionName: "ftx-processor"
  producerName: "ftx-processor"
  operationTimeout: 30s
  connectionTimeout: 30s

ftx:
  apiUrl: https://ftx.com/api
  websocketUrl: "wss://ftx.com/ws/"
  timeout: 10
  orderBook:
    markets:
      - market: ETH-PERP
