pulsar:
  url: "pulsar://localhost:6650"
  subscriptionName: "ftx-processor"
  producerName: "ftx-processor"

ftx:
  websocketUrl: "wss://ftx.com/ws/"
  orderBook:
    markets:
      - market: ETH-PERP
