version: "3.8"

services:
  binance-processor:
    image: ${DOCKER_REGISTRY-}binanceprocessor
    build:
      context: .
      dockerfile: exchange/binance-processor/Dockerfile
      target: local
    restart: unless-stopped
    depends_on:
      - postgresdb
      - pulsar
    networks:
      - omiga_network
