app:
  source: "urn::omiga::binance-processor"

pulsar:
  url: "pulsar://localhost:6650"
  subscriptionName: "binance-processor"
  producerName: "binance-processor"

postgres:
  connectionString: "postgres://postgres:12345678@localhost/exchange"
  maxOpenConns: 5

binance:
  useTestnet: true
  orderBook:
    symbols:
      - symbol1: LTC
        symbol2: BTC
