app:
  source: "urn::omiga::binance-processor"

pulsar:
  url: "pulsar://localhost:6650"
  subscriptionName: "binance-processor"
  producerName: "binance-processor"

binance:
  useTestnet: true
  orderBook:
    symbols:
      - symbol: LTCBTC
        purgeTime: 30m
