// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Currency is the predicate function for currency builders.
type Currency func(*sql.Selector)

// Market is the predicate function for market builders.
type Market func(*sql.Selector)

// Outbox is the predicate function for outbox builders.
type Outbox func(*sql.Selector)

// Ticker is the predicate function for ticker builders.
type Ticker func(*sql.Selector)

// TradingPair is the predicate function for tradingpair builders.
type TradingPair func(*sql.Selector)

// Venue is the predicate function for venue builders.
type Venue func(*sql.Selector)
