// Code generated by MockGen. DO NOT EDIT.
// Source: trading_pair_subscriber.go

// Package mock_subscribers is a generated GoMock package.
package mock_subscribers

import (
	gomock "github.com/golang/mock/gomock"
)

// MockKuCoinTradingPairSubscriber is a mock of KuCoinTradingPairSubscriber interface.
type MockKuCoinTradingPairSubscriber struct {
	ctrl     *gomock.Controller
	recorder *MockKuCoinTradingPairSubscriberMockRecorder
}

// MockKuCoinTradingPairSubscriberMockRecorder is the mock recorder for MockKuCoinTradingPairSubscriber.
type MockKuCoinTradingPairSubscriberMockRecorder struct {
	mock *MockKuCoinTradingPairSubscriber
}

// NewMockKuCoinTradingPairSubscriber creates a new mock instance.
func NewMockKuCoinTradingPairSubscriber(ctrl *gomock.Controller) *MockKuCoinTradingPairSubscriber {
	mock := &MockKuCoinTradingPairSubscriber{ctrl: ctrl}
	mock.recorder = &MockKuCoinTradingPairSubscriberMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKuCoinTradingPairSubscriber) EXPECT() *MockKuCoinTradingPairSubscriberMockRecorder {
	return m.recorder
}
