const { GoGenerator } = require("@asyncapi/modelina");
const { File } = require("@asyncapi/generator-react-sdk");

export default async function ({ asyncapi, params }) {
  const generator = new GoGenerator({
    presets: [
      {
        struct: {
          field({ fieldName, field, renderer, type, model: { required } }) {
            const formattedFieldName = renderer.nameField(fieldName, field);
            const fieldType = renderer.renderType(field);

            const description = field.originalInput
              ? ` // ${field.originalInput["description"]}`
              : "";

            const isRequired =
              required.findIndex((item) => item === fieldName) !== -1;
            const unrequiredMark = !isRequired ? "*" : "";

            const format = field.originalInput
              ? field.originalInput["format"]
              : "";
            let finalFieldType = fieldType.startsWith("*")
              ? fieldType.substring(1)
              : fieldType;

            switch (format) {
              case "date-time":
                finalFieldType = "time.Time";
                break;

              case "uuid":
                finalFieldType = "ID";
                break;

              default:
                break;
            }

            return `${formattedFieldName} ${unrequiredMark}${finalFieldType} \`json:"${fieldName}"${
              !isRequired ? ",omitempty" : ""
            }\`${description}`;
          },
        },
      },
    ],
  });
  const models = await generator.generate(asyncapi);

  let payloadContent = `
// Code generated by go-omiga-template, DO NOT EDIT.

package ${params.packageName}

import (
	"strings"
	"time"

	"github.com/google/uuid"
)

type ID struct {
  UUID uuid.UUID
}
`;

  const payloadUtils = `
func (i *ID) UnmarshalJSON(b []byte) error {
  if parsedUuid, err := uuid.Parse(strings.Trim(string(b), "\\"")); err == nil {
    i.UUID = parsedUuid
  } else {
    return err
  }

  return nil
}
`;

  models.forEach((model) => {
    payloadContent += `
    ${model.dependencies.join("\n")}
    ${model.result}
    `;
  });

  payloadContent += payloadUtils;

  return <File name="payloads_gen.go">{payloadContent}</File>;
}
