openapi: 3.0.1
info:
  title: Xt API V1
  description: "Xt REST API"
  version: 1.0.0

servers:
  - url: https://api.xt.com/data/api/v1

paths:
  /getMarketConfig:
    get:
      tags:
      - spot
      summary: fetches the supported market configs
      operationId: getAllMarketConfig
      responses:
        200:
          description: list of market configs
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/getMarketConfigResponse"

components:
  schemas:
    getMarketConfigResponse:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/marketConfig'

    marketConfig:
      type: object
      additionalProperties: true
      required:
        - minAmount
        - pricePoint
        - coinPoint
        - maker
        - minMoney
        - taker
      properties:
        minAmount:
          type: number
          format: double
        pricePoint:
          type: integer
        coinPoint:
          type: integer
        maker:
          type: number
          format: double
        minMoney:
          type: number
          format: double
        taker:
          type: number
          format: double
