app:
  listeningInterface: ":10000"
  source: "urn::omiga::order-api"

pulsar:
  url: "pulsar://pulsar.localhost:6650"
  producerName: "order-api"

postgres:
  connectionString: "postgres://postgres:12345678@postgres.localhost/order"
  maxOpenConns: 10

outbox:
  maxRetryCount: 30
  retryDelay: 10s
