app:
  source: "urn::omiga::huobi-processor"

exchange:
  id: "huobi"

pulsar:
  url: "pulsar://localhost:6650"
  subscriptionName: "huobi-processor"
  producerName: "huobi-processor"
  operationTimeout: 30s
  connectionTimeout: 30s

postgres:
  connectionString: "postgres://postgres:12345678@localhost/exchange"
  maxOpenConns: 5

huobi:
  baseUrl: "api.huobi.pro"
  apiKey: ""
  secretKey: ""
