version: "3.8"

services:
  web:
    image: ${DOCKER_REGISTRY-}web
    build:
      context: ..
      dockerfile: src/web/Dockerfile
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      GRAPHQL_API_ENDPOINT: http://localhost:4343
    profiles:
      - web
      - all
    networks:
      - omiga_network
