version: "3.9"

networks:
  omiga_apis_network:

services:
  order-api:
    image: microbusiness/web:latest
    restart: unless-stopped
    environment:
      OMIGA_APP_LISTENINGINTERFACE: ":80"
      GRAPHQL_API_ENDPOINT: $GRAPHQL_API_ENDPOINT
    ports:
      - "$OMIGA_WEB_PORT:80"
    networks:
      - omiga_apis_network
