version: '3.8'

networks:
  omiga_network:


volumes:
  omiga_pulsar_data:
  omiga_postgres_data:


services:
  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
    networks:
      - omiga_network

  postgres:
    image: postgres:14.4-alpine
    restart: unless-stopped
    volumes:
      - omiga_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "12345678"
    ports:
      - "5432:5432"
    networks:
      - omiga_network

  pulsar:
    image: apachepulsar/pulsar:latest
    command: bin/pulsar standalone
    hostname: pulsar
    ports:
      - "8080:8080"
      - "6650:6650"
    restart: unless-stopped
    volumes:
      - omiga_pulsar_data:/pulsar/data
    networks:
      - omiga_network

  pulsar-dashboard:
    image: apachepulsar/pulsar-manager:latest
    ports:
      - "9527:9527"
      - "7750:7750"
    depends_on:
      - pulsar
    links:
      - pulsar
    environment:
      SPRING_CONFIGURATION_FILE: /pulsar-manager/pulsar-manager/application.properties
    networks:
      - omiga_network
