version: "3.9"

networks:
  omiga_apis_network:

services:
  order-api:
    image: microbusiness/order-api:latest
    restart: unless-stopped
    environment:
      OMIGA_POSTGRES_CONNECTIONSTRING: $OMIGA_POSTGRES_CONNECTIONSTRING
    networks:
      - omiga_apis_network

  venue-api:
    image: microbusiness/venue-api:latest
    restart: unless-stopped
    environment:
      OMIGA_POSTGRES_CONNECTIONSTRING: $OMIGA_POSTGRES_CONNECTIONSTRING
    networks:
      - omiga_apis_network

  gateway:
    image: microbusiness/gateway:latest
    restart: unless-stopped
    environment:
      ORDER_GRAPHQL_API: http://order-api/graphql
      EXCHANGE_GRAPHQL_API: http://venue-api/graphql
    ports:
      - "$OMIGA_GATEWAY_PORT:80"
    networks:
      - omiga_apis_network
