version: "3.8"

networks:
  omiga_venues_network:

services:
  venues-all-in-one:
    image: microbusiness/venues-all-in-one:latest
    restart: unless-stopped
    environment:
      OMIGA_POSTGRES_CONNECTIONSTRING: $OMIGA_POSTGRES_CONNECTIONSTRING
      OMIGA_RAIN_USERNAME: $OMIGA_RAIN_USERNAME
      OMIGA_RAIN_PASSWORD: $OMIGA_RAIN_PASSWORD
      OMIGA_RAIN_TOTPSECRET: $OMIGA_RAIN_TOTPSECRET
      OMIGA_RAIN_TIMEOUT: $OMIGA_RAIN_TIMEOUT
    networks:
      - omiga_venues_network
