version: "3.8"

networks:
  omiga_apis_network:

services:
  order-api:
    image: microbusiness/order-api:latest
    restart: unless-stopped
    environment:
      OMIGA_APP_LISTENINGINTERFACE: ":80"
      OMIGA_POSTGRES_CONNECTIONSTRING: $OMIGA_POSTGRES_CONNECTIONSTRING_ORDER
    networks:
      - omiga_apis_network

  venue-api:
    image: microbusiness/venue-api:latest
    restart: unless-stopped
    environment:
      OMIGA_APP_LISTENINGINTERFACE: ":80"
      OMIGA_POSTGRES_CONNECTIONSTRING: $OMIGA_POSTGRES_CONNECTIONSTRING_VENUE
    networks:
      - omiga_apis_network

  gateway:
    image: microbusiness/gateway:latest
    restart: unless-stopped
    environment:
      PORT: "80"
      ORDER_GRAPHQL_API: http://order-api/graphql
      VENUE_GRAPHQL_API: http://venue-api/graphql
    ports:
      - "$OMIGA_GATEWAY_PORT:80"
    networks:
      - omiga_apis_network
