// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package appsetup

import (
	"github.com/omiga-group/omiga/src/shared/enterprise/database"
	"github.com/omiga-group/omiga/src/shared/enterprise/database/postgres"
	"github.com/omiga-group/omiga/src/shared/enterprise/os"
	"github.com/omiga-group/omiga/src/venue/shared/entities"
	"go.uber.org/zap"
)

// Injectors from wire.go:

func NewDatabase(logger *zap.SugaredLogger, postgresConfig postgres.PostgresConfig) (database.Database, error) {
	databaseDatabase, err := postgres.NewPostgres(logger, postgresConfig)
	if err != nil {
		return nil, err
	}
	return databaseDatabase, nil
}

func NewEntgoClient(logger *zap.SugaredLogger, postgresConfig postgres.PostgresConfig) (entities.EntgoClient, error) {
	databaseDatabase, err := postgres.NewPostgres(logger, postgresConfig)
	if err != nil {
		return nil, err
	}
	entgoClient, err := entities.NewEntgoClient(logger, databaseDatabase)
	if err != nil {
		return nil, err
	}
	return entgoClient, nil
}

func NewOsHelper() (os.OsHelper, error) {
	osHelper, err := os.NewOsHelper()
	if err != nil {
		return nil, err
	}
	return osHelper, nil
}
