
// Code generated by go-omiga-template, DO NOT EDIT.

package orderv1

import (
	"context"
	"encoding/json"

	"github.com/omiga-group/omiga/src/shared/enterprise/messaging"
	"go.uber.org/zap"
)

type Consumer interface {
	StartAsync(ctx context.Context) error
	Close()
}

type consumer struct {
	logger                 *zap.SugaredLogger
	subscriber             Subscriber
	messageConsumer messaging.MessageConsumer
}

func NewConsumer(
	logger *zap.SugaredLogger,
	subscriber Subscriber,
	messageConsumer messaging.MessageConsumer) Consumer {
	return &consumer{
		logger:                 logger,
		subscriber:             subscriber,
		messageConsumer: messageConsumer,
	}
}

func (c *consumer) StartAsync(ctx context.Context) error {
	go func() {
		for {
			if ctx.Err() == context.Canceled {
				return
			}

			message, messageProcessedCallback, messageFailedCallback, err := c.messageConsumer.Consume(ctx, TopicName)
			if err != nil && err == context.Canceled {
				return
			} else if err != nil && err != context.Canceled {
				c.logger.Errorf("Failed to consume message. Error: %v", err)

				continue
			}

			event := OrderEvent{}
			if err := json.Unmarshal(message.Payload, &event); err != nil {
				c.logger.Errorf("Failed to de-serialize OrderEvent message. Error: %v", err)

				messageFailedCallback()

				continue
			}

			if err := c.subscriber.Handle(ctx, event); err != nil {
				c.logger.Errorf("Failed to handle OrderEvent message. Error: %v", err)

				messageFailedCallback()

				continue
			}

			messageProcessedCallback()
		}
	}()

	return nil
}

func (c *consumer) Close()  {
	c.messageConsumer.Close()
}
