app:
  source: "urn::omiga::rain-processor"

pulsar:
  url: "pulsar://localhost:6650"
  subscriptionName: "rain-processor"
  producerName: "rain-processor"
  operationTimeout: 30s
  connectionTimeout: 30s

postgres:
  connectionString: "postgres://postgres:12345678@localhost/venue"
  maxOpenConns: 5

rain:
  id: "rain"
  websiteUrl: "https://www.rain.com"
  baseUrl: "https://smart-prod-0.rain.com/api/1"
  username: "morteza.alizadeh@gmail.com"
  password: "1qaz@WSXhjkl;'"
  totpSecret: "W653BKW55ZICVOMPAV53T4HGG7JT235RQ3KI43IQ7EA2MBJD54UQ"
  headless: true
  timeout: 30s
