name: "Base Docker Images"

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/base-docker-images.yml"
      - "src/shared/base-docker-images/**"
  pull_request:
    branches:
      - "main"
    paths:
      - ".github/workflows/base-docker-images.yml"
      - "src/shared/base-docker-images/**"

jobs:
  build-go-playwright:
    name: "Build - go-playwright Base Docker Images"
    runs-on:
      - self-hosted
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1

    steps:
      - name: Checkout code with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set required environment variable
        run: |
          echo "sem_version=$(docker run --rm -v $(pwd):/repo gittools/gitversion:5.11.1-alpine.3.13-6.0 /repo | jq '.SemVer')" >> $GITHUB_ENV

      - name: Build
        run: |
          DOCKER_BUILDKIT=1 VERSION=${{ env.sem_version }} docker build \
             --pull \
            --tag microbusiness/go-playwright:${{ github.sha }} \
            --file ./src/shared/base-docker-images/Dockerfile.go.playwright \
            ./src/shared/base-docker-images

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: microbusiness/go-playwright:${{ github.sha }}
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
          timeout: "10m0s"

      - name: Login to Docker Hub
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push docker image
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker tag \
            microbusiness/go-playwright:${{ github.sha }} \
            microbusiness/go-playwright:latest
          docker tag \
            microbusiness/go-playwright:${{ github.sha }} \
            microbusiness/go-playwright:${{ env.sem_version }}
          docker push microbusiness/go-playwright:${{ env.sem_version }}
          docker push microbusiness/go-playwright:${{ github.sha }}
          docker push microbusiness/go-playwright:latest

      - name: Clean up
        if: always()
        run: |
          docker rmi microbusiness/go-playwright:${{ env.sem_version }} || true
          docker rmi microbusiness/go-playwright:${{ github.sha }} || true
          docker rmi microbusiness/go-playwright:latest || true

  build-atlas:
    name: "Build - atlas Base Docker Images"
    runs-on:
      - self-hosted
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1

    steps:
      - name: Checkout code with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set required environment variable
        run: |
          echo "sem_version=$(docker run --rm -v $(pwd):/repo gittools/gitversion:5.11.1-alpine.3.13-6.0 /repo | jq '.SemVer')" >> $GITHUB_ENV

      - name: Build
        run: |
          DOCKER_BUILDKIT=1 VERSION=${{ env.sem_version }} docker build \
             --pull \
            --tag microbusiness/atlas:${{ github.sha }} \
            --file ./src/shared/base-docker-images/Dockerfile.atlas \
            ./src/shared/base-docker-images

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: microbusiness/atlas:${{ github.sha }}
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL"
          timeout: "10m0s"

      - name: Login to Docker Hub
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push docker image
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker tag \
            microbusiness/atlas:${{ github.sha }} \
            microbusiness/atlas:latest
          docker tag \
            microbusiness/atlas:${{ github.sha }} \
            microbusiness/atlas:${{ env.sem_version }}
          docker push microbusiness/atlas:${{ env.sem_version }}
          docker push microbusiness/atlas:${{ github.sha }}
          docker push microbusiness/atlas:latest

      - name: Clean up
        if: always()
        run: |
          docker rmi microbusiness/atlas:${{ env.sem_version }} || true
          docker rmi microbusiness/atlas:${{ github.sha }} || true
          docker rmi microbusiness/atlas:latest || true
