name: "Bittrex Processor"

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/codeql-analysis.yml"
      - ".github/workflows/lint.yml"
      - ".github/workflows/bittrex-processor.yml"
      - "src/go.mod"
      - "src/go.sum"
      - "src/shared/**"
      - "src/venue/shared/**"
      - "src/venue/bittrex-processor/**"
  pull_request:
    branches:
      - "main"
    paths:
      - ".github/workflows/codeql-analysis.yml"
      - ".github/workflows/lint.yml"
      - ".github/workflows/bittrex-processor.yml"
      - "src/go.mod"
      - "src/go.sum"
      - "src/shared/**"
      - "src/venue/shared/**"
      - "src/venue/bittrex-processor/**"

jobs:
  build:
    name: "Build - Bittrex Processor"
    runs-on:
      - self-hosted
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1

    steps:
      - name: Set required environment variable
        run: |
          echo "unittest_extract_container_tag=$(uuidgen)" >> $GITHUB_ENV
          echo "unittest_extract_container_name=$(uuidgen)" >> $GITHUB_ENV

      - name: Checkout code with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build
        run: |
          DOCKER_BUILDKIT=1 VERSION=${{ github.sha }} docker build \
             --pull \
             --target build \
            --file ./src/venue/bittrex-processor/Dockerfile \
            ./src

      - name: Unit Tests
        run: |
          DOCKER_BUILDKIT=1 VERSION=${{ github.sha }} docker build \
             --pull \
             --target test \
            --tag ${{ env.unittest_extract_container_tag }} \
            --file ./src/venue/bittrex-processor/Dockerfile \
            ./src
          mkdir -p ./coverage/reports
          docker create --name ${{ env.unittest_extract_container_name }} ${{ env.unittest_extract_container_tag }}
          docker cp ${{ env.unittest_extract_container_name }}:/coverage/reports/. "./coverage/reports/"

      - name: Upload coverage to Codecov
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/reports/
          flags: unittests,bittrex-processor
          fail_ci_if_error: true
          verbose: true

      - name: Build final
        run: |
          DOCKER_BUILDKIT=1 VERSION=${{ github.sha }} docker build \
             --pull \
             --target final \
            --tag omiga/bittrex-processor:${{ github.sha }} \
            --file ./src/venue/bittrex-processor/Dockerfile \
            ./src

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: omiga/bittrex-processor:${{ github.sha }}
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
          timeout: "10m0s"

      - name: Clean up
        if: always()
        run: |
          docker rm ${{ env.unittest_extract_container_tag }} || true
          docker rm ${{ env.unittest_extract_container_name }} || true

      - name: Clean up
        if: always()
        run: |
          docker rm ${{ env.unittest_extract_container_tag }} || true
          docker rm ${{ env.unittest_extract_container_name }} || true
