name: "Coingecko Processor"

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/codeql-analysis.yml"
      - ".github/workflows/lint.yml"
      - ".github/workflows/coingecko-processor.yml"
      - "src/go.mod"
      - "src/go.sum"
      - "src/shared/**"
      - "src/venue/shared/**"
      - "src/venue/coingecko-processor/**"
  pull_request:
    branches:
      - "main"
    paths:
      - ".github/workflows/codeql-analysis.yml"
      - ".github/workflows/lint.yml"
      - ".github/workflows/coingecko-processor.yml"
      - "src/go.mod"
      - "src/go.sum"
      - "src/shared/**"
      - "src/venue/shared/**"
      - "src/venue/coingecko-processor/**"

jobs:
  build:
    name: "Build - Coingecko Processor"
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1

    steps:
      - name: Checkout code with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.13
        with:
          versionSpec: "5.x"

      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.9.13
        with:
          useConfigFile: true
          configFilePath: GitVersion.yml

      - name: Build
        run: |
          DOCKER_BUILDKIT=1 VERSION=$GitVersion_SemVer docker build \
             --pull \
             --target build \
            --file ./src/venue/coingecko-processor/Dockerfile \
            ./src

      - name: Unit Tests
        run: |
          DOCKER_BUILDKIT=1 VERSION=$GitVersion_SemVer docker build \
             --pull \
             --target test \
            --tag omiga/coingecko-processor-unittests:$GitVersion_SemVer \
            --file ./src/venue/coingecko-processor/Dockerfile \
            ./src
          mkdir -p ./coverage/reports
          docker create --name extract-container omiga/coingecko-processor-unittests:$GitVersion_SemVer
          docker cp extract-container:/coverage/reports/. "./coverage/reports/"

      - name: Upload coverage to Codecov
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/reports/
          flags: unittests,coingecko
          fail_ci_if_error: true
          verbose: true

      - name: Build final
        run: |
          DOCKER_BUILDKIT=1 VERSION=$GitVersion_SemVer docker build \
             --pull \
             --target final \
            --tag omiga/coingecko-processor:$GitVersion_SemVer \
            --tag omiga/coingecko-processor:${{ github.sha }} \
            --file ./src/venue/coingecko-processor/Dockerfile \
            ./src
          docker save -o image.tar omiga/coingecko-processor:$GitVersion_SemVer

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: omiga/coingecko-processor:${{ github.sha }}
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
          timeout: "10m0s"
