name: "Gateway"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: "Build - Gateway"
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1

    steps:
      - name: Checkout code with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: dorny/paths-filter@v2.10.2
        id: filter
        with:
          filters: |
            relevant_directories_changed:
              - '.github/workflows/codeql-analysis.yml'
              - '.github/workflows/lint.yml'
              - '.github/workflows/gateway.yml'
              - 'src/gateway/**'

      - name: Install GitVersion
        if: ${{ steps.filter.outputs.relevant_directories_changed == 'true' }}
        uses: gittools/actions/gitversion/setup@v0.9.13
        with:
          versionSpec: "5.x"

      - name: Determine Version
        if: ${{ steps.filter.outputs.relevant_directories_changed == 'true' }}
        uses: gittools/actions/gitversion/execute@v0.9.13
        with:
          useConfigFile: true
          configFilePath: GitVersion.yml

      - name: Build final
        if: ${{ steps.filter.outputs.relevant_directories_changed == 'true' }}
        run: |
          DOCKER_BUILDKIT=1 VERSION=$GitVersion_SemVer docker build \
             --pull \
            --tag omiga/gateway:$GitVersion_SemVer \
            --tag omiga/gateway:${{ github.sha }} \
            --file ./src/gateway/Dockerfile \
            ./src

      - name: Run Trivy vulnerability scanner
        if: ${{ steps.filter.outputs.relevant_directories_changed == 'true' }}
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: omiga/gateway:${{ github.sha }}
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
          timeout: "10m0s"
