name: "Gateway"

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/lint.yml"
      - ".github/workflows/gateway.yml"
      - "src/gateway/**"
  pull_request:
    branches:
      - "main"
    paths:
      - ".github/workflows/lint.yml"
      - ".github/workflows/gateway.yml"
      - "src/gateway/**"

jobs:
  build:
    name: "Build - Gateway"
    runs-on:
      - self-hosted
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1

    steps:
      - name: Checkout code with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set required environment variable
        run: |
          echo "sem_version=$(docker run --rm -v $(pwd):/repo gittools/gitversion:5.10.3-alpine.3.13-6.0 /repo | jq '.SemVer')" >> $GITHUB_ENV

      - name: Build final
        run: |
          DOCKER_BUILDKIT=1 VERSION=${{ github.sha }} docker build \
             --pull \
            --tag microbusiness/gateway:${{ env.sem_version }} \
            --tag microbusiness/gateway:${{ github.sha }} \
            --file ./src/gateway/Dockerfile \
            ./src

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: microbusiness/gateway:${{ github.sha }}
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
          timeout: "10m0s"

      - name: Clean up
        if: always()
        run: |
          docker rmi microbusiness/gateway:${{ env.sem_version }} || true
          docker rmi microbusiness/gateway:${{ github.sha }} || true
