name: Lint

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/lint.yml"
      - "src/**"
  pull_request:
    branches:
      - "main"
    paths:
      - ".github/workflows/lint.yml"
      - "src/**"

jobs:
  golangci:
    name: Lint
    runs-on:
      - self-hosted
    steps:
      - name: Checkout code with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run lint
        run: |
          cd ./src
          make lint
