name: Lint

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/lint.yml"
      - "src/**"
  pull_request:
    branches:
      - "main"
    paths:
      - ".github/workflows/lint.yml"
      - "src/**"

jobs:
  golangci:
    name: Lint
    runs-on:
      - self-hosted
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.48

          # Optional: working directory, useful for monorepos
          working-directory: src

          # Optional: golangci-lint command line arguments.
          # args: --issues-exit-code=0
          args: --timeout=3m

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true
