name: "Order Processor"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: "Build - Order Processor"
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1

    steps:
      - name: Checkout code with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: dorny/paths-filter@v2.10.2
        id: filter
        with:
          filters: |
            relevant_directories_changed:
              - '.github/workflows/codeql-analysis.yml'
              - '.github/workflows/lint.yml'
              - '.github/workflows/order-processor.yml'
              - 'src/go.mod'
              - 'src/go.sum'
              - 'src/shared/**'
              - 'src/order/shared/**'
              - 'src/order/order-processor/**'

      - name: Install GitVersion
        if: ${{ steps.filter.outputs.relevant_directories_changed == 'true' }}
        uses: gittools/actions/gitversion/setup@v0.9.13
        with:
          versionSpec: "5.x"

      - name: Determine Version
        if: ${{ steps.filter.outputs.relevant_directories_changed == 'true' }}
        uses: gittools/actions/gitversion/execute@v0.9.13
        with:
          useConfigFile: true
          configFilePath: GitVersion.yml

      - name: Build, test and tag the Docker image
        if: ${{ steps.filter.outputs.relevant_directories_changed == 'true' }}
        run: |
          DOCKER_BUILDKIT=1 VERSION=$GitVersion_SemVer docker build --pull \
            --tag omiga/order-processor:$GitVersion_SemVer \
            --file ./src/order/order-processor/Dockerfile \
            ./src

  success:
    name: "Success - Order Processor"
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Success
        run: |
          echo "Completed"
