name: "Order Shared"

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/codeql-analysis.yml"
      - ".github/workflows/lint.yml"
      - ".github/workflows/order-shared.yml"
      - "src/go.mod"
      - "src/go.sum"
      - "src/shared/**"
      - "src/order/shared/**"
  pull_request:
    branches:
      - "main"
    paths:
      - ".github/workflows/codeql-analysis.yml"
      - ".github/workflows/lint.yml"
      - ".github/workflows/order-shared.yml"
      - "src/go.mod"
      - "src/go.sum"
      - "src/shared/**"
      - "src/order/shared/**"

jobs:
  build:
    name: "Build - Order Shared"
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1

    steps:
      - name: Checkout code with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.13
        with:
          versionSpec: "5.x"

      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.9.13
        with:
          useConfigFile: true
          configFilePath: GitVersion.yml

      - name: Unit Tests
        run: |
          DOCKER_BUILDKIT=1 VERSION=$GitVersion_SemVer docker build \
             --pull \
             --target test \
            --tag omiga/order-shared-unittests:$GitVersion_SemVer \
            --file ./src/order/shared/Dockerfile \
            ./src
          mkdir -p ./coverage/reports
          docker create --name extract-container omiga/order-shared-unittests:$GitVersion_SemVer
          docker cp extract-container:/coverage/reports/. "./coverage/reports/"

      - name: Upload coverage to Codecov
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/reports/
          flags: unittests,order-shared
          fail_ci_if_error: true
          verbose: true
