name: "Shared"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: "Build - Shared"
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1

    steps:
      - name: Checkout code with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: dorny/paths-filter@v2.10.2
        id: filter
        with:
          filters: |
            relevant_directories_changed:
              - '.github/workflows/codeql-analysis.yml'
              - '.github/workflows/lint.yml'
              - '.github/workflows/shared.yml'
              - 'src/go.mod'
              - 'src/go.sum'
              - 'src/shared/**'

      - name: Install GitVersion
        if: ${{ steps.filter.outputs.relevant_directories_changed == 'true' }}
        uses: gittools/actions/gitversion/setup@v0.9.13
        with:
          versionSpec: "5.x"

      - name: Determine Version
        if: ${{ steps.filter.outputs.relevant_directories_changed == 'true' }}
        uses: gittools/actions/gitversion/execute@v0.9.13
        with:
          useConfigFile: true
          configFilePath: GitVersion.yml

      - name: Unit Tests
        if: ${{ steps.filter.outputs.relevant_directories_changed == 'true' }}
        run: |
          DOCKER_BUILDKIT=1 VERSION=$GitVersion_SemVer docker build \
             --pull \
             --target test \
            --tag omiga/shared-unittests:$GitVersion_SemVer \
            --file ./src/shared/Dockerfile \
            ./src
          mkdir -p ./coverage/reports
          docker create --name extract-container omiga/shared-unittests:$GitVersion_SemVer
          docker cp extract-container:/coverage/reports/. "./coverage/reports/"

      - name: Upload coverage to Codecov
        if: ${{ steps.filter.outputs.relevant_directories_changed == 'true' && github.ref == 'refs/heads/main' }}
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/reports/
          flags: unittests,shared
          fail_ci_if_error: true
          verbose: true
