name: "Web"

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/lint.yml"
      - ".github/workflows/web.yml"
      - "api-definitions/graphql/microbusiness/**"
      - "src/web/**"
  pull_request:
    branches:
      - "main"
    paths:
      - ".github/workflows/lint.yml"
      - ".github/workflows/web.yml"
      - "api-definitions/graphql/microbusiness/**"
      - "src/web/**"

jobs:
  build:
    name: "Build - Web"
    runs-on:
      - self-hosted
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1

    steps:
      - name: Checkout code with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set required environment variable
        run: |
          echo "build_container_tag=$(uuidgen)" >> $GITHUB_ENV
          echo "unittest_container_tag=$(uuidgen)" >> $GITHUB_ENV
          echo "unittest_extract_container_name=$(uuidgen)" >> $GITHUB_ENV
          echo "sem_version=$(docker run --rm -v $(pwd):/repo gittools/gitversion:5.10.3-alpine.3.13-6.0 /repo | jq '.SemVer')" >> $GITHUB_ENV

      - name: Build
        run: |
          DOCKER_BUILDKIT=1 VERSION=${{ github.sha }} docker build \
             --pull \
            --tag microbusiness/web:${{ github.sha }} \
            --file ./src/web/Dockerfile \
            ./

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: microbusiness/web:${{ github.sha }}
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
          timeout: "10m0s"

      - name: Login to Docker Hub
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push docker image
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker tag \
            microbusiness/web:${{ github.sha }} \
            microbusiness/web:latest
          docker tag \
            microbusiness/web:${{ github.sha }} \
            microbusiness/web:${{ env.sem_version }}
          docker push microbusiness/web:${{ env.sem_version }}
          docker push microbusiness/web:${{ github.sha }}
          docker push microbusiness/web:latest

      - name: Clean up
        if: always()
        run: |
          docker rm ${{ env.unittest_extract_container_name }} || true
          docker rmi ${{ env.build_container_tag }} || true
          docker rmi ${{ env.unittest_container_tag }} || true
          docker rmi microbusiness/web:${{ env.sem_version }} || true
          docker rmi microbusiness/web:${{ github.sha }} || true

  deploy-to-dev:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: "Deploying to Dev"
    needs: build
    runs-on:
      - self-hosted
    steps:
      - name: Setting up SSH Agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_GITHUB_ACTION }}

      - name: Deploy
        run: |
          ssh ${{ secrets.PROD_SERVER_SSH_HOST_ADDRESS }} -p ${{ secrets.PROD_SERVER_SSH_PORT }} -o StrictHostKeyChecking=no "/root/omiga-restart-web-dev.sh"
