name: "Web"

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/codeql-analysis.yml"
      - ".github/workflows/lint.yml"
      - ".github/workflows/web.yml"
      - "api-definitions/graphql/omiga/**"
      - "src/web/**"
  pull_request:
    branches:
      - "main"
    paths:
      - ".github/workflows/codeql-analysis.yml"
      - ".github/workflows/lint.yml"
      - ".github/workflows/web.yml"
      - "api-definitions/graphql/omiga/**"
      - "src/web/**"

jobs:
  build:
    name: "Build - Web"
    runs-on:
      - self-hosted
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1

    steps:
      - name: Checkout code with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build
        run: |
          DOCKER_BUILDKIT=1 VERSION=${{ github.sha }} docker build \
             --pull \
            --tag omiga/web:${{ github.sha }} \
            --file ./src/web/Dockerfile \
            ./

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: omiga/web:${{ github.sha }}
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
          timeout: "10m0s"
